SUBJECTS = [
    {"name": "Mathematics",        "code": "MATH",  "grade_level_min": 1,  "grade_level_max": 12, "required_weekly_periods": 5},
    {"name": "English Language",   "code": "ENG",   "grade_level_min": 1,  "grade_level_max": 12, "required_weekly_periods": 5},
    {"name": "Science",            "code": "SCI",   "grade_level_min": 1,  "grade_level_max": 6,  "required_weekly_periods": 4},
    {"name": "History",            "code": "HIST",  "grade_level_min": 4,  "grade_level_max": 12, "required_weekly_periods": 3},
    {"name": "Geography",          "code": "GEO",   "grade_level_min": 4,  "grade_level_max": 12, "required_weekly_periods": 3},
    {"name": "Physical Education", "code": "PE",    "grade_level_min": 1,  "grade_level_max": 12, "required_weekly_periods": 2},
    {"name": "Art",                "code": "ART",   "grade_level_min": 1,  "grade_level_max": 9,  "required_weekly_periods": 2},
    {"name": "Music",              "code": "MUS",   "grade_level_min": 1,  "grade_level_max": 9,  "required_weekly_periods": 2},
    {"name": "Computer Science",   "code": "CS",    "grade_level_min": 4,  "grade_level_max": 12, "required_weekly_periods": 3},
    {"name": "Biology",            "code": "BIO",   "grade_level_min": 7,  "grade_level_max": 12, "required_weekly_periods": 4},
    {"name": "Chemistry",          "code": "CHEM",  "grade_level_min": 7,  "grade_level_max": 12, "required_weekly_periods": 4},
    {"name": "Physics",            "code": "PHY",   "grade_level_min": 7,  "grade_level_max": 12, "required_weekly_periods": 4},
    {"name": "Economics",          "code": "ECON",  "grade_level_min": 9,  "grade_level_max": 12, "required_weekly_periods": 3},
    {"name": "Literature",         "code": "LIT",   "grade_level_min": 7,  "grade_level_max": 12, "required_weekly_periods": 3},
    {"name": "Malay Language",     "code": "MAL",   "grade_level_min": 1,  "grade_level_max": 12, "required_weekly_periods": 3},
    {"name": "Mandarin",           "code": "MAN",   "grade_level_min": 1,  "grade_level_max": 12, "required_weekly_periods": 3},
    {"name": "Tamil",              "code": "TAM",   "grade_level_min": 1,  "grade_level_max": 12, "required_weekly_periods": 3},
    {"name": "Moral Education",    "code": "MORAL", "grade_level_min": 1,  "grade_level_max": 12, "required_weekly_periods": 1},
]
